### ISSUE TITLE
Use Node.js and Express.js to create RESTFul API

### ISSUE THREAD

**Issue by mmlawton15** [barrantesc/The-Sheet-Show#1]
## RESTful API fully built and functional with Node.js and Express. Working locally and hosted on Heroku.

- #19 
     - [x] @ErikPlachta onboarded template content 
- #19 , #21 , #35 , #37 
     - [x] @mmlawton15 @NicaVulcan and @barrantesc verified root integrity 
- [ ] Team to final review and then close this issue.

**Comment by ErikPlachta** [comment]
## @mmlawton15 This is completed. If you want to do a final review and close?
