### ISSUE TITLE
Heroku: Protect API Keys and Sensitive Information with ENV var

### ISSUE THREAD

**Issue by mmlawton15** [barrantesc/The-Sheet-Show#12]
## All Sensitive Information is within Environment Variables at https://dashboard.heroku.com/apps/sheet-show/settings

- [x] Remove the placeholder seed variable, create a new one, and add it to the environment variables in Heroku
- [x] Verify if anything else

**Comment by ErikPlachta** [comment]
If we need to do this, it's done in Heroku here: https://dashboard.heroku.com/apps/sheet-show/settings
![image](https://user-images.githubusercontent.com/17508965/153109832-d0e23c01-e622-4ef8-a543-4f975ef3fb69.png)
