### ISSUE TITLE
README: Have a quality README with a unique name, description, technologies used, screenshot and link to deployed application

### ISSUE THREAD

**Issue by mmlawton15** [barrantesc/The-Sheet-Show#14]

**Comment by mmlawton15** [comment]
Going to add to this as we go along the project, feel free to embellish as you see fit! Assuming we are going to use the Heroku link for deployment, but correct me if i am wrong!

**Comment by ErikPlachta** [comment]
## Attaching GIFs for README to a pull request and adding not here how to link into readme and control size.

@mmlawton15 FYI

```markdown
<img src="./public/homepage.gif" width="1200">
```

```markdown
<img src="./public/nav-login-logout.gif" width="1200">
```

```markdown
<img src="./public/my-heros-character-sheet-profile-sheet.gif" width="1200">
```

**Comment by barrantesc** [comment]
DONE!
