### ISSUE TITLE
Character deletion

### ISSUE THREAD

**Issue by NicaVulcan** [barrantesc/The-Sheet-Show#145]
A user should only be able to delete their own characters. Modal that pops up when character is clicked could be a small menu instead of whole character card. If in home page, options are limited to viewing character details. If in personal profile, options include viewing and editing character details, and deleting character.

**Comment by ErikPlachta** [comment]
@NicaVulcan You did this?

**Comment by NicaVulcan** [comment]
@ErikPlachta sorry, yeah, I was writing issues for myself to work on in my own form and didn’t realize it was adding them to the main repo instead of my fork. There’s a few I made, just ignore those, that’s my bad.
