### ISSUE TITLE
DB: Build Database Framework

### ISSUE THREAD

**Issue by ErikPlachta** [barrantesc/The-Sheet-Show#15]
## Frame out Concept for Seed Data

//-- users is logging into our app
user = {
    id
    username
    email
    password
}

//-- Characters is created by users logged into app
character = {
    id
    user_id
    name
    race
    class
    gender
}

**Comment by ErikPlachta** [comment]
@mmlawton15 is managing building framework

**Comment by mmlawton15** [comment]
Finished during class, just need to seed the files but i think Erik is doing that!

**Comment by ErikPlachta** [comment]
> @mmlawton15 is managing building framework

Looks like we're good to go with this on Pull Request #21 , we just need to finish the merge
