### ISSUE TITLE
Routes: Build Routes Framework

### ISSUE THREAD

**Issue by ErikPlachta** [barrantesc/The-Sheet-Show#16]
## Routes are fully functional and verified.

**Comment by ErikPlachta** [comment]
### @NicaVulcan I believe this is completed. Can you verify and close if so or let us know otherwise?

**Comment by ErikPlachta** [comment]
_Confirmed in Slack that @NicaVulcan  is aware and will manage today!_

**Comment by NicaVulcan** [comment]
Verified this is done! Issue closed!
