### ISSUE TITLE
Controller: MySQL2 and the Sequelize as ORMs for JawsDB and MySQL

### ISSUE THREAD

**Issue by mmlawton15** [barrantesc/The-Sheet-Show#3]
### Controller uses MySQL2 and Sequelize for ORM local MySQL and JawsDatabase on Heroku

- [x] Onboarded
- [x] Verified by full team
- [x] @barrantesc to review and close issue once confirmed good

**Comment by ErikPlachta** [comment]
## Reviewed and confirmed this is completed. Updating Issue and requested @barrantesc close.

**Comment by barrantesc** [comment]
Good great!
