### ISSUE TITLE
Feature: Hero Graphics - Create a basic image for each race

### ISSUE THREAD

**Issue by mmlawton15** [barrantesc/The-Sheet-Show#49]
## Add Feature: Hero Graphics - Create a basic image for each race

**Comment by ErikPlachta** [comment]
## Added and verified working locally and on Heroku.

Sent to them for review on #50 

![image](https://user-images.githubusercontent.com/17508965/153773642-3664ed4e-9f92-44ac-8ce4-86ba4c693c9a.png)
