### ISSUE TITLE
Hosting: Deployed on Heroku & Verified Integrity

### ISSUE THREAD

**Issue by mmlawton15** [barrantesc/The-Sheet-Show#5]
## Deploy APP on Heroku

- [x] **1.** Build Heroku URL: https://dashboard.heroku.com/apps/sheet-show
- [x] **2.** Share with everyone
- [x] **3.** Push APP to Heroku
     - This is running but it's not yet fully verified. That will require Controller configuration on #18 which is something @barrantesc was working on last night
- [x] **4.** Add JawsDB Resources
- [x] **5.** Verify able to communicate with API server

**Comment by ErikPlachta** [comment]
Created server for this and shared with the group
> https://dashboard.heroku.com/apps/sheet-show

**Comment by ErikPlachta** [comment]
## Pushing to Heroku and verifying integirty now

- [x] Pushed to Heroku with command `git push Heroku develop:main` 
- [ ] Verify it's posted correctly
   - [ ] Can I talk to server /  Does server respond to API calls?
- [ ] Notify Team
- [ ] Close Issue

**Comment by ErikPlachta** [comment]
## 4. Add JawsDB Resources

![image](https://user-images.githubusercontent.com/17508965/153723835-f96ba3f2-1aa6-485e-a555-ab822c5109a5.png)

**Comment by ErikPlachta** [comment]
## 5. Verify able to communicate with API server

Confirmed running and creating new Issue for Error

![image](https://user-images.githubusercontent.com/17508965/153723866-dfd49464-e9e3-44e8-9c21-1a99ecfeeb4c.png)
