### ISSUE TITLE
Character Creator functionality

### ISSUE THREAD

**Issue by NicaVulcan** [barrantesc/The-Sheet-Show#52]
Behind the curtain of the Character Creator page: 
___
- [x] Retrieve necessary info from DnD API: 
  - [x] Fetch Race Info:
    - Alignment
    - Ability Bonuses
    - Languages
    - Size Description
  - [x] Fetch Class Info: 
    - Proficiency choices allowed
    - Proficiency choices
___
- [x] Create calculating functions: 
  - [x] Ability Scores Calculations: 
    - Ability scores are traditionally calculated by rolling 4 D6 and dropping the lowest number. To simulate this, user will be able to press a button for each ability and yield a random number from 6-18.
  - [x] Modifiers Calculations: 
    - Modifiers are traditionally calculated by subtracting 10 from the ability score, and dividing the result by 2.
  - [x] Proficiency Bonus Calculations: 
    - Proficiency bonuses are calculated based on the Player Level (which can be from 1 - 20). Calculations are as follows: 
       | Player Level | Proficiency Bonus |
        | --- | ----- |
        | 1 - 4 | +2 |
        | 5 - 8 | +3 |
        | 9 -12 | +4 |
        | 13 - 16 | +5 |
        | 17 - 20 | +6 |
  - [x] Ability Bonuses: 
    - Ability Bonuses are determined by the race of the character. These will be retrieved from the api and passed into a function that will add the bonuses to the respective abilities.

**Comment by ErikPlachta** [comment]
## Great work here, ty for updating and managing 🧠
