### ISSUE TITLE
Feature: Use at least one new library, PKG or New Software/Technology

### ISSUE THREAD

**Issue by mmlawton15** [barrantesc/The-Sheet-Show#6]
### -R&D on Potential Options
   - @ErikPlachta
       - NPM Packages
           - https://www.npmjs.com/package/dnd-character-sheets
           - https://www.npmjs.com/package/fantasy-content-generator
           - https://www.npmjs.com/package/dyslexic-charactersheets
 
   - @mmlawton15 
       - CSS Bootstrap
           - https://docs.siimple.xyz/

### Decide what to Do

- [ ] What do we know how to do?
- [ ] What do we _need_ to do?

### Make a Plan

- [ ] ??

**Comment by mmlawton15** [comment]
Will use siimple!
https://docs.siimple.xyz/

Picnic is backup

**Comment by ErikPlachta** [comment]
@NicaVulcan 

## Did you get a chance to review the NPM Packages we've found?

- #33 #25 
That would qualify for this issue
